import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ZRehman InfoTech",
  description: "Generated by create next app",
  icons: {
    icon: "/Images/logo.png", // standard favicon
    shortcut: "/Images/logo.png", // shortcut icon for some browsers
    apple: "/Images/logo.png", // Apple touch icon
  },
};

import Footer from "components/Home/Footer";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
